#!/bin/bash
mv jtool2 jtool2_orin
lipo jtool2_orin -thin x86_64 -output jtool2_x86_64
lipo jtool2_orin -thin arm64 -output jtool2_arm64
./ldid -r jtool2_arm64
install_name_tool -change /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation jtool2_arm64
./ios2mac_jtool2 jtool2_arm64
./ldid -S -Cadhoc -Clinker-signed jtool2_arm64
lipo -create -output jtool2 jtool2_arm64 jtool2_x86_64
rm jtool2_arm64 jtool2_x86_64

mv disarm disarm_orin
lipo disarm_orin -thin x86_64 -output disarm_x86_64
lipo disarm_orin -thin arm64 -output disarm_arm64
./ldid -r disarm_arm64
./ios2mac_disarm disarm_arm64
./ldid -S -Cadhoc -Clinker-signed disarm_arm64
lipo -create -output disarm disarm_arm64 disarm_x86_64
rm disarm_arm64 disarm_x86_64

